### PR TITLE
Pull Request for #99: Revise channel priority setting when building conda

### LINKED ISSUE #99: Revise channel priority setting when building conda
Per https://github.com/gentzkow/template/issues/62#issuecomment-1306413158, we decided to set up the strict channel priority in conda to reduce the build time of environment. However, setting channel priority strict at the same time limit the search of packages in a certain channel. For example, attached is an error I encountered in `SearchMarket` project.

<details>

```zsh
SIEPR-C02G50GUML86:SearchMarket shiqiyang$     conda env create -f setup/conda_env.yaml
Channels:
 - conda-forge
 - r
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: / warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
failed
Channels:
 - conda-forge
 - r
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: / warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package r-amr-2.1.1-r43h6115d3f_0 requires r-base >=4.3,<4.4.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ r-amr is installable and it requires
│  └─ r-base >=4.3,<4.4.0a0  with the potential options
│     ├─ r-base [4.3.0|4.3.1] would require
│     │  └─ icu >=72.1,<73.0a0 , which can be installed;
│     └─ r-base [4.3.1|4.3.2|4.3.3] would require
│        └─ icu >=73.2,<74.0a0 , which conflicts with any installable versions previously reported;
└─ r-unicode is not installable because there are no viable options
   ├─ r-unicode 14.0.0_1 would require
   │  └─ r-base >=4.2,<4.3.0a0  but there are no viable options
   │     ├─ r-base [4.2.0|4.2.1|4.2.2|4.2.3] would require
   │     │  └─ icu >=70.1,<71.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ r-base 4.2.3 would require
   │     │  └─ icu >=73.2,<74.0a0 , which conflicts with any installable versions previously reported;
   │     └─ r-base 4.2.3 would require
   │        └─ icu >=72.1,<73.0a0 , which can be installed;
   ├─ r-unicode 12.0.0_1 would require
   │  └─ r-base >=3.6,<3.7.0a0  but there are no viable options
   │     ├─ r-base 3.6.1 would require
   │     │  └─ clang_osx-64 4.*  but there are no viable options
   │     │     ├─ clang_osx-64 4.0.1 would require
   │     │     │  └─ clang 4.0.1.*  but there are no viable options
   │     │     │     ├─ clang 4.0.1 would require
   │     │     │     │  └─ compiler-rt 4.0.1 hcfea43d_1, which conflicts with any installable versions previously reported;
   │     │     │     ├─ clang 4.0.1 would require
   │     │     │     │  └─ libcxx 4.0.1 h579ed51_0, which conflicts with any installable versions previously reported;
   │     │     │     └─ clang 4.0.1 conflicts with any installable versions previously reported;
   │     │     └─ clang_osx-64 4.0.1 conflicts with any installable versions previously reported;
   │     ├─ r-base [3.6.1|3.6.2|3.6.3] would require
   │     │  └─ icu >=64.2,<65.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ r-base 3.6.3 would require
   │     │  └─ icu >=68.1,<69.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ r-base 3.6.3 would require
   │     │  └─ icu >=67.1,<68.0a0 , which conflicts with any installable versions previously reported;
   │     └─ r-base [3.6.0|3.6.1] conflicts with any installable versions previously reported;
   └─ r-unicode [12.0.0_1|14.0.0_1|15.0.0_1] conflicts with any installable versions previously reported.

```

</details>

The error got resolved when I revert the channel `strict` priority setting back to `flexible`. We need to revise our `README.md` file to recommend user to set `channel_priority` strict, instead of asking them to set strict channel priority by default.

### PR DESCRIPTION
**Pull request by ShiqiYang2022**
Closes #99.

The proposed changes see [here](https://github.com/gentzkow/template/pull/100/files). More details see https://github.com/gentzkow/template/issues/99#issue-2249371013 and [comment](https://github.com/huntallcott/SearchMarket/issues/149#issuecomment-2062551654).

I am requesting @jc-cisneros to review, thanks in advance! Let me know whether you agree with the proposed changes.

### CODE REVIEW

**Comment by jc-cisneros** [comment]
@ShiqiYang2022, working on this. I will let you know if I have any questions.

**Review by jc-cisneros — COMMENTED** [review]
@ShiqiYang2022, my vote is that we keep `channel_priority strict` as the default instruction. A flexible channel configuration can make building an environment take significantly more time (specially if it contains both Python and R packages).

We can then add the caveat that if the channel specified in the yaml file does not have all the required packages/versions, they can go back to the default configuration (i.e., setting it to "flexible"). Let me know what you think.

**Comment by ShiqiYang2022** [comment]
@jc-cisneros See 47e2f39, let me know whether they looks good to you, thanks!

**Review by jc-cisneros — APPROVED** [review]
The changes in the instructions look good @ShiqiYang2022. I proposed a [minor change](https://github.com/gentzkow/template/pull/100/files/47e2f39d902b48af62ed1f96987c4e709567a863..74a7e74fa0cffc6dbce758acb6107cfb72efcf60#r1607092479) that you can implement. Feel free to merge once you are happy with the language. Thanks @ShiqiYang2022!

**Comment by ShiqiYang2022** [comment]
**Summary**

In this issue we revised conda setup. Changes brought to `master` in cf9cc9c.

Final state of the branch [here](https://github.com/gentzkow/template/pull/100/commits/cf9cc9c958b4998be589224a585cdff1e43ad785).

**Pull request merged**
