### PR TITLE
PR for #45: Simplify make.py

### LINKED ISSUE #45: Simplify make.py
I thought this might be a good time to take a look at the structure of the `make.py` scripts and see if there's any way we can streamline them. 

Here are some comments / questions

1. The "Load GSLab Make" section is awkward. I don't remember what caused us to have such a complicated loading step here. It would be great if we could just say `import gslab_make` at the top. 

2. "Check if running from root to check conda status" is a little obscure. Can we clarify what we're doing here?

3. I don't like "Uncomment for Stata scripts" on line 49. It looks like this is anticipating a situation where we might want to add a `temp` directory at the top level of the module for outputs we don't want to store/commit (something we do often for Stata scripts). But if we're not including that directory in the template better to just delete this. I wonder if it wouldn't be better practice actually to make that directory `output/temp` so the `make.py` script doesn't have to be modified

4. Line 52 should say something like "MAKE LINKS TO INPUT AND EXTERNAL FILES"

Any other improvements you can suggest?

### PR DESCRIPTION
**Pull request by szahedian**
Closes #45.

This PR simplifies and streamlines template make scripts. Specific changes made are outlined in [this](https://github.com/gentzkow/template/issues/45#issue-974853290) and [this](https://github.com/gentzkow/template/issues/45#issuecomment-902073834) comments.

### CODE REVIEW

**Comment by szahedian** [comment]
@Houdanait thanks for agreeing to peer review!

The changes are to the three `make.py` scripts and the default `config.yaml`. Please let me know if the new setup functions for you, is confusing, or you foresee any trouble with it.

**Comment by szahedian** [comment]
Since my earlier comment, we've made two categories of changes to the repo
1. Restructure Stata and R scripts within `template`. These have been moved to a separate folder, and need to be copied over in order to be run. 
2. Accompanying the change in (1), an explanation of how to use `template` with Stata and R.

**Comment by Houdanait** [comment]
@szahedian Thank you so much for pushing all these. I would have a few questions, so let's coordinate on Slack when we can meet/call to discuss ?

**Comment by Houdanait** [comment]
Hello @szahedian ! Thank you so much for all the updates you implemented ! It really looks great :)

I have a  comment to make. 

1. The extensions folder is not clear to a random user. When you open it, there is no ReadMe at the root of the folder, so the person is left without information upon clicking that repository. Then, they have to check `/R` subfolder or `/stata` subfolder to understand what the root `/extensions` folder is meant for. I think it would make sense to have a readMe at the root to explain the purpose of `/extensions`, since `/r` and `/stata` are similar.

**Comment by szahedian** [comment]
Thanks @Houdanait for that comment! You are exactly right that consolidating those READMEs into a single one is both clearer and less redundant. I've made that change. 

If you want to quickly look at `extensions/README.md` and let me know it's clear, I'll go ahead and merge!

**Pull request merged**
