### PR TITLE
PR for #86: reformat template to fit tex compile

### LINKED ISSUE #86: Reformat template to fit `.tex` compile
In this issue we will reformat the template to substitute from `.lyX` to `.tex` compile for our standard paper development process.

Goals of this issue:

- [x] Switch the `.lyx` formats in `paper_slides/code` to `.tex` formats
- [x] Move the `Lyx` version of `paper_slides` into `extensions/lyx`.
- [x] Compare `.tex` compile locally vs. Overleaf compile. Investigate on how to manage differences.

This issue is originated from https://github.com/gentzkow/template/issues/84#issuecomment-1650960177 and is related to https://github.com/gentzkow/template/issues/85.

cc: @gentzkow @jc-cisneros @snairdesai

### PR DESCRIPTION
**Pull request by ShiqiYang2022**
Closes #86 .

This PR aim to review the reformat of template compile in #86. The purpose of this issue is described in https://github.com/gentzkow/template/issues/86#issue-1886725615. For this PR, I suggest the following steps:

- [x] Populate the newest `gslab_make` in https://github.com/gslab-econ/gslab_make/issues/64 into `template/lib`.
- [x] Complete the full run of the template using `.tex` compile.
- [x] Complete the full run using `.lyx`, please refer to the ReadMe file [here](https://github.com/gentzkow/template/blob/645e27840d746a77a58f265af6ad3937c2893a2c/README.md#running-package-scripts-in-other-languages). 
- [x] Check the diffs between (1) `.lyx` and `.tex` compile; (2) local `.tex` compile and Overleaf compile.

Per conversation, @snairdesai has bandwidth to conduct the review. @snairdesai please flag any error or anything that might not be clear in any of the steps. 

cc: @gentzkow @jc-cisneros

### CODE REVIEW

**Comment by snairdesai** [comment]
_Update:_ Per conversation with @ShiqiYang2022, this is probably a new conflict arising from the Mac `M2` chip on my local machine. Even the standard `template` is no longer on my local machine (though it did previously) which suggests something was updated in the `conda` environment which is no longer supported by Apple Silicon.

A new issue will be opened to address this; in the meantime @jc-cisneros will take over testing here.

**Comment by ShiqiYang2022** [comment]
@snairdesai Thanks for testing! I have requested @jc-cisneros to test this on his Macbook with intel chip.

**Comment by jc-cisneros** [comment]
@ShiqiYang2022 if I try to re-run the `.tex` compile, I get this error:

```
*********************************************************
* Error with `run_latex`. Traceback can be found below. *
*********************************************************

Traceback (most recent call last):
  File "/Users/jccp/Desktop/template/paper_slides/../lib/gslab_make/gslab_make/run_program.py", line 283, in run_latex
    os.mkdir('latex_auxiliary_dir')
FileExistsError: [Errno 17] File exists: 'latex_auxiliary_dir'
```

Perhaps you could add a check that if this directory exists, then continue.

**Comment by jc-cisneros** [comment]
Confirming everything works as expected @ShiqiYang2022! Per our conversation, if the `paper_slides` module fails, the temporary directory will not be cleared and we will not be able to re-run the module until we erase it. Confirming this is intentional because that would provide us with intermediate output that we can use to fix any error.

**Comment by ShiqiYang2022** [comment]
@jc-cisneros Thanks! This is because in your previous run, you did not populate the updated the `gslab_make`, and it got stuck since it cannot correctly refer the nested `.tex` file. When you manually killed the terminal, the session ended and `latex_auxiliary_dir` remained with intermediate output. 

Per our conversation you did not delete this folder when you re-run `.tex`. And this `latex_auxiliary_dir` has the necessity for its existence, because it can help us check the intermediate outputs. I think all good here!

**Comment by ShiqiYang2022** [comment]
The follow-up issue of https://github.com/gentzkow/template/pull/88#issuecomment-1769301802 is opened in #89.

**Comment by ShiqiYang2022** [comment]
@jc-cisneros Given the problem described in https://github.com/gentzkow/template/pull/88#issuecomment-1769301802 is addressed in #89 #90, maybe it's a good time to give it another review, thanks!

**Review by jc-cisneros — APPROVED** [review]
Thanks @ShiqiYang2022! My understanding is there were no changes in the code after my last review. Given that the only remaining lingering [comment](https://github.com/gentzkow/template/pull/88#issuecomment-1769301802) was addressed in a separate issue, this looks good to go.

**Comment by ShiqiYang2022** [comment]
@gentzkow 

We shifted `template` compile from `.lyx` to `.tex` in this PR and #86, and I am closing this PR and merging back.

Per [#84(Comment)](https://github.com/gentzkow/template/issues/84#:~:text=lab%2Dmanual%20appendix.-,One%20open%20loop%20is%20how%20to%20manage%20differences%20in%20the%20Tex%20installation%20on%20Overleaf%20vs.%20our%20local%20machines.%20We%20definitely%20want%20to%20make%20sure%20the%20PDFs%20compile%20locally.%20Can%20you%20remind%20me%20the%20status%20of%20that%20issue%3F,-%F0%9F%91%80), we want to compare `.tex` compile locally vs Overleaf and manage the difference properly. The difference can be properly managed by specifying the version of `TexLive` distribution consistent with that used in Overleaf, and (if co-author use other `.tex` distributions) use the packages that only are part of the standard TeX distribution. For details, please see https://github.com/gentzkow/template/issues/86#issuecomment-1768660960.

**Comment by gentzkow** [comment]
Great. Thanks! 

Can we

1. Make sure we add a `/lyx/` directory to `/extensions/` that has the Lyx version of `paper_slides`. 

2. Make sure our instructions for Overleaf include the note about how to make sure it's consistent w/ local compile.

**Comment by ShiqiYang2022** [comment]
@gentzkow Thanks! Replies to this https://github.com/gentzkow/template/pull/88#issuecomment-1777498066:

1. This has been done in 87f5afc. @jc-cisneros has cross-checked that we can complete the full run moving back `.lyx`, following the instructionsof the [ReadMe file](https://github.com/gentzkow/template/blob/645e27840d746a77a58f265af6ad3937c2893a2c/README.md#running-package-scripts-in-other-languages).
2. I just added that part into the instructions (ref: [here](https://github.com/ShiqiYang2022/template/wiki/Overleaf%E2%80%90GitHub-Synchronization#manage-difference-between-overleaf-compile-and-local-tex-compile)).

**Pull request merged**
